### ISSUE TITLE
Failed to set value 'slow' for option 'preset'

### ISSUE THREAD

**Issue by jcollum-hcg** [Ilias95/FF-Multi-Converter#28]
Trying to convert ogv to mpg. When I convert it fails I get this: 

``` 
Stream mapping:
  Stream #0.1 -> #0.0
  Stream #0.2 -> #0.1
Error while opening encoder for output stream #0.0 - maybe incorrect parameters such as bit_rate, rate, width or height
```

That's pretty vague. The command line is `-ab 320k -ar 48000 -ac 2`. 

I don't see anything in my presets (pressing "Preset" button brings up a window that has no presets in it) or anything about what I'm supposed to put in that command line. 

OK so I found the presets and imported them. It still errors out: 

```
ffmpeg -y -i "/home/dev/temp/thefilename.ogv" -crf 35.0 -vcodec libx264 -preset slow -acodec libfaac -ar 48000 -b:a 128k -coder 1 -flags +loop -cmp chroma -partitions +parti4x4+partp8x8+partb8x8 -me_method hex -subq 6 -me_range 16 -g 250 -keyint_min 25 -sc_threshold 40 -i_qfactor 0.71 -b_strategy 1 -threads 0 "/home/dev/temp/thefilename.mp4"
ffmpeg version 0.8.10-4:0.8.10-0ubuntu0.12.04.1, Copyright (c) 2000-2013 the Libav developers
  built on Feb  6 2014 20:56:59 with gcc 4.6.3
*** THIS PROGRAM IS DEPRECATED ***
This program is only provided for compatibility and will be removed in a future release. Please use avconv instead.
[ogg @ 0x13077a0] max_analyze_duration reached
Input #0, ogg, from '/home/dev/temp/thefilename.ogv':
  Duration: 00:00:43.66, start: 0.000000, bitrate: 541 kb/s
    Stream #0.0: Data: skeleton
    Stream #0.1: Video: theora, yuv420p, 1584x1040 [PAR 1:1 DAR 99:65], 15 fps, 15 tbr, 15 tbn, 15 tbc
    Stream #0.2: Audio: vorbis, 22050 Hz, mono, s16, 89 kb/s
Unrecognized option 'preset'
Failed to set value 'slow' for option 'preset'
```

Just installed an hour ago. Looks like this preset has an issue.

**Comment by Ilias95** [comment]
Hi again and sorry for the huge delay on giving feedback to this.

Finally, the first issue with the preset option has to do with the incompatibility of ffmpeg and avconv/libav. The two programs are not fully compatible in their options (although the compatibility is satisfactory in most cases) and ffmulticonverter mainly supports ffmpeg. One solution is to directly use ffmpeg instead of avconv (on ubuntu the ffmpeg command just calls the avconv program so you have to install ffmpeg from your package manager).

Regarding the presets issue you can view this post https://github.com/Ilias95/FF-Multi-Converter/issues/32#issuecomment-76461103 and check if the new -coming soon- version of ffmulticonverter runs properly for you without any presets issues.

Thank you and sorry again for the late reply.
