### ISSUE TITLE
Split the 'From - To' list.

### ISSUE THREAD

**Issue by pooky2483** [Ilias95/FF-Multi-Converter#44]
When converting documents, instead of having a drop-down menu which lists the from - to list, why not have a separate drop down for each. it would be easier selecting the format to convert from and to being separate lists.

**Comment by pooky2483** [comment]
How do I make this a 'Feature Request'

**Comment by Ilias95** [comment]
The problem is that there's no one-to-one correspondence. Not all formats can be converted to every else format.

Although, it seems that unoconv/libreoffice now supports much more conversions between formats. So, I will sure add more options in a future release.

> How do I make this a 'Feature Request'

You can add a label from the menu on the right. I did it for you.

**Comment by Ilias95** [comment]
Done: 45f7530ad710dff4b7a5fd6425e3fdc6ed60c378

I actually left only the 'To' list and added a few file formats. The program will try the conversions with any given input.

I will implement a way for the user to manually add extra document formats in a way similar to the existing for videos and images (through Preferences).
