### ISSUE TITLE
Is the project under active development?

### ISSUE THREAD

**Issue by Petross404** [Ilias95/FF-Multi-Converter#57]
Hello, I want to port this package to the gentoo repo and I am wondering if FF-Multi-Converter is still under development.

Thanks :)

**Comment by Ilias95** [comment]
Hello.

The truth is that lately I'm not working on new issues nor there are plans to do so soon because of luck of time. I'm trying to maintain the project when I can, so bug fixes etc. will be fixed. 

The version 1.8.0 is supposed to be stable so feel free to package it for gentoo and provide me with a link.

Thank you.

**Comment by Petross404** [comment]
Thank you for your responce :)
